version: "3.9"

services:
  app:
    build: .
    container_name: google-ads-reports
    ports:
      - "3005:3000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
